// Code generated by protoc-gen-go. DO NOT EDIT.
// source: echo.proto

/*
Package echo is a generated protocol buffer package.

It is generated from these files:
	echo.proto

It has these top-level messages:
	EchoRequest
	EchoResponse
*/
package echo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int64  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *EchoRequest) Reset()                    { *m = EchoRequest{} }
func (m *EchoRequest) String() string            { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()               {}
func (*EchoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EchoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EchoRequest) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type EchoResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int64  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EchoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EchoResponse) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "echo.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "echo.EchoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Echoer service

type EchoerClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	EchoAgain(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	EchoStream(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (Echoer_EchoStreamClient, error)
}

type echoerClient struct {
	cc *grpc.ClientConn
}

func NewEchoerClient(cc *grpc.ClientConn) EchoerClient {
	return &echoerClient{cc}
}

func (c *echoerClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/echo.Echoer/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoerClient) EchoAgain(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/echo.Echoer/EchoAgain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoerClient) EchoStream(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (Echoer_EchoStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Echoer_serviceDesc.Streams[0], c.cc, "/echo.Echoer/EchoStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoerEchoStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Echoer_EchoStreamClient interface {
	Recv() (*EchoResponse, error)
	grpc.ClientStream
}

type echoerEchoStreamClient struct {
	grpc.ClientStream
}

func (x *echoerEchoStreamClient) Recv() (*EchoResponse, error) {
	m := new(EchoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Echoer service

type EchoerServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	EchoAgain(context.Context, *EchoRequest) (*EchoResponse, error)
	EchoStream(*EchoRequest, Echoer_EchoStreamServer) error
}

func RegisterEchoerServer(s *grpc.Server, srv EchoerServer) {
	s.RegisterService(&_Echoer_serviceDesc, srv)
}

func _Echoer_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoerServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.Echoer/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoerServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echoer_EchoAgain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoerServer).EchoAgain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.Echoer/EchoAgain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoerServer).EchoAgain(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echoer_EchoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EchoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoerServer).EchoStream(m, &echoerEchoStreamServer{stream})
}

type Echoer_EchoStreamServer interface {
	Send(*EchoResponse) error
	grpc.ServerStream
}

type echoerEchoStreamServer struct {
	grpc.ServerStream
}

func (x *echoerEchoStreamServer) Send(m *EchoResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Echoer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "echo.Echoer",
	HandlerType: (*EchoerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Echoer_Echo_Handler,
		},
		{
			MethodName: "EchoAgain",
			Handler:    _Echoer_EchoAgain_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EchoStream",
			Handler:       _Echoer_EchoStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "echo.proto",
}

func init() { proto.RegisterFile("echo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4d, 0xce, 0xc8,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x8c, 0xb9, 0xb8, 0x5d, 0x93,
	0x33, 0xf2, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73,
	0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x01, 0x2e, 0xe6, 0xc4, 0xf4,
	0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x10, 0x53, 0xc9, 0x84, 0x8b, 0x07, 0xa2, 0xa9,
	0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x95, 0x38, 0x5d, 0x46, 0x2b, 0x18, 0xb9, 0xd8, 0x40, 0xda, 0x52,
	0x8b, 0x84, 0xf4, 0xb9, 0x58, 0x40, 0x2c, 0x21, 0x41, 0x3d, 0xb0, 0x83, 0x90, 0x5c, 0x20, 0x25,
	0x84, 0x2c, 0x04, 0x31, 0x5f, 0x89, 0x41, 0xc8, 0x84, 0x8b, 0x13, 0x24, 0xe2, 0x98, 0x9e, 0x98,
	0x99, 0x47, 0xbc, 0x2e, 0x73, 0x2e, 0x2e, 0x90, 0x48, 0x70, 0x49, 0x51, 0x6a, 0x62, 0x2e, 0xd1,
	0xda, 0x0c, 0x18, 0x93, 0xd8, 0xc0, 0x41, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x60,
	0x6c, 0x22, 0x30, 0x01, 0x00, 0x00,
}
